### PR TITLE
feat: upstreaming baselines and reverting styling changes

### PR DESCRIPTION
**Pull request by Ashish13898**
This PR contains changes related to upstreaming the main branch with latest changes of the parent repo of Guacamol Baselines and reverting the black styling changes to match with the parent repo.

### CODE REVIEW

**Review by drugilsberg — COMMENTED** [review]
Looks great, we have to consider creating a frag_gt algorithm in gt4sd-core.
Also consider upgrading the version of the python package.

**Comment by Ashish13898** [comment]
> Looks great, we have to consider creating a frag_gt algorithm in gt4sd-core. Also consider upgrading the version of the python package.

I will start looking into that :)

Also it seems like they wanted to treat the frag_at implementation as a single package as they have added a separate setup.py and directory for this algorithm.

Should we keep it as it is or change the directory structure merge the dependencies of frag_at with baselines dependencies?

**Comment by drugilsberg** [comment]
what about keeping it as is and have our setup.py installing the two packages?

**Comment by Ashish13898** [comment]
> what about keeping it as is and have our setup.py installing the two packages?

That makes more sense, l will look into that and modify our setup.py to install two packages :)

**Review by drugilsberg — APPROVED** [review]

**Review by drugilsberg — APPROVED** [review]
Looks good

**Pull request merged**
